<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; font-size: 13px; color: #333; margin: 0; padding: 30px; }
        .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
        .company-name { font-size: 24px; font-weight: bold; color: #2563eb; }
        .invoice-title { font-size: 20px; font-weight: bold; color: #374151; }
        .invoice-number { color: #6b7280; font-size: 14px; }
        .info-grid { display: flex; gap: 40px; margin-bottom: 30px; }
        .info-block { flex: 1; }
        .info-label { font-size: 11px; color: #9ca3af; text-transform: uppercase; margin-bottom: 4px; }
        .info-value { font-size: 13px; color: #374151; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #f3f4f6; padding: 10px 12px; text-align: left; font-size: 11px; text-transform: uppercase; color: #6b7280; }
        td { padding: 10px 12px; border-bottom: 1px solid #e5e7eb; }
        .text-right { text-align: right; }
        .totals-table { width: 260px; margin-left: auto; }
        .totals-table td { border: none; padding: 4px 0; }
        .total-row { font-weight: bold; font-size: 15px; border-top: 2px solid #e5e7eb; padding-top: 8px; }
        .status-badge { display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: bold; }
        .status-paid { background: #d1fae5; color: #065f46; }
        .status-unpaid { background: #fef3c7; color: #92400e; }
        .notes { margin-top: 20px; padding: 12px; background: #f9fafb; border-radius: 6px; }
        .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 11px; }
    </style>
</head>
<body>

<!-- Header -->
<div class="header">
    <div>
        <div class="company-name">{{ auth()->user()->name }}</div>
        <div style="color:#6b7280;margin-top:4px">{{ auth()->user()->email }}</div>
    </div>
    <div style="text-align:right">
        <div class="invoice-title">INVOICE</div>
        <div class="invoice-number">{{ $invoice->invoice_number }}</div>
        <div style="margin-top:8px">
            <span class="status-badge {{ $invoice->status === 'paid' ? 'status-paid' : 'status-unpaid' }}">
                {{ strtoupper($invoice->status) }}
            </span>
        </div>
    </div>
</div>

<!-- Invoice info + Bill to -->
<div class="info-grid">
    <div class="info-block">
        <div class="info-label">Bill to</div>
        <div class="info-value" style="font-weight:bold">{{ $invoice->client->name }}</div>
        <div class="info-value">{{ $invoice->client->email }}</div>
        <div class="info-value">{{ $invoice->client->phone }}</div>
        <div class="info-value">{{ $invoice->client->address }}</div>
    </div>
    <div class="info-block">
        <div class="info-label">Issue date</div>
        <div class="info-value">{{ $invoice->issue_date->format('d M Y') }}</div>
        <div class="info-label" style="margin-top:10px">Due date</div>
        <div class="info-value">{{ $invoice->due_date->format('d M Y') }}</div>
    </div>
</div>

<!-- Items table -->
<table>
    <thead>
        <tr>
            <th>Description</th>
            <th class="text-right">Qty</th>
            <th class="text-right">Unit price</th>
            <th class="text-right">Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach($invoice->items as $item)
        <tr>
            <td>{{ $item->description }}</td>
            <td class="text-right">{{ $item->quantity }}</td>
            <td class="text-right">৳{{ number_format($item->unit_price, 2) }}</td>
            <td class="text-right">৳{{ number_format($item->total, 2) }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

<!-- Totals -->
<table class="totals-table">
    <tr>
        <td>Subtotal</td>
        <td class="text-right">৳{{ number_format($invoice->subtotal, 2) }}</td>
    </tr>
    @if($invoice->discount_percent > 0)
    <tr style="color:#dc2626">
        <td>Discount ({{ $invoice->discount_percent }}%)</td>
        <td class="text-right">-৳{{ number_format($invoice->subtotal * $invoice->discount_percent / 100, 2) }}</td>
    </tr>
    @endif
    @if($invoice->tax_percent > 0)
    <tr>
        <td>Tax ({{ $invoice->tax_percent }}%)</td>
        <td class="text-right">+৳{{ number_format($invoice->total - ($invoice->subtotal * (1 - $invoice->discount_percent/100)), 2) }}</td>
    </tr>
    @endif
    <tr class="total-row">
        <td>Total</td>
        <td class="text-right">৳{{ number_format($invoice->total, 2) }}</td>
    </tr>
</table>

@if($invoice->notes)
<div class="notes">
    <strong>Notes:</strong> {{ $invoice->notes }}
</div>
@endif

<div class="footer">
    Thank you for your business — Generated by InvoiceApp
</div>

</body>
</html>